### ISSUE TITLE
unable to create the environment 

### ISSUE THREAD

**Issue by learner-3f1719** [pacm/dl-workshop#1]
after the :
"conda env create -f environment-windows.yml"
i got the following outcome;

"Solving environment: failed

ResolvePackageNotFound:
  - pytorch-cpu=0.4.0"

any hints?

**Comment by ghost** [comment]
What your version of Windows? Do you have the 32-bit or the 64-bit version?

**Comment by learner-3f1719** [comment]
i use Windows 10 32-bit

conda 4.5.4

Python 3.6.4 :: Anaconda custom (32-bit)

**Comment by ghost** [comment]
Re-update: I didn't find a way to install PyTorch on a Windows 32-bit version - if you find one, please let me know.

In any case, that won't be an issue because you can run the notebooks in the cloud without prior installation with the following mybinder.org links

[![Binder Notebook](https://img.shields.io/badge/binder-Jupyter%20Notebook-blue.svg)](https://mybinder.org/v2/gh/pacm/dl-workshop/master) [![Binder Notebook](https://img.shields.io/badge/binder-Juypter%20Lab-blue.svg)](https://mybinder.org/v2/gh/pacm/dl-workshop/master?urlpath=lab)

So, just make sure that you have a recent browser - I would recommend using Chrome.
